version: 2.1
jobs:
  build-node15:
    docker:
      - image: circleci/node:15
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci

  build-node14:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci

  build-node12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci

  release:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci
      - run: npx semantic-release

workflows:
  version: 2
  build_and_release:
    jobs:
      - build-node15
      - build-node14
      - build-node12
      - release:
          requires:
            - build-node15
            - build-node14
            - build-node12